-- Lista mínima das 54 Parashot para a página /parashot aparecer no site.
-- Rode no Supabase: SQL Editor → New query → colar → Run.
-- Seguro rodar mais de uma vez (upsert por slug).

INSERT INTO public.parashot (slug, name, name_hebrew, book, week_number, summary, is_premium)
VALUES
  ('bereshit', 'Bereshit', 'בראשית', 'Bereshit', 1, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('noach', 'Noach', 'נח', 'Bereshit', 2, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('lech-lecha', 'Lech-Lecha', 'לך־לך', 'Bereshit', 3, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vayera', 'Vayera', 'וירא', 'Bereshit', 4, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('chayei-sarah', 'Chayei-Sarah', 'חיי שרה', 'Bereshit', 5, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('toldot', 'Toldot', 'תולדות', 'Bereshit', 6, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vayetze', 'Vayetze', 'ויצא', 'Bereshit', 7, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vayishlach', 'Vayishlach', 'וישלח', 'Bereshit', 8, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vayeshev', 'Vayeshev', 'וישב', 'Bereshit', 9, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('miketz', 'Miketz', 'מקץ', 'Bereshit', 10, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vayigash', 'Vayigash', 'ויגש', 'Bereshit', 11, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vayechi', 'Vayechi', 'ויחי', 'Bereshit', 12, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('shemot', 'Shemot', 'שמות', 'Shemot', 13, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vaera', 'Vaera', 'וארא', 'Shemot', 14, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('bo', 'Bo', 'בא', 'Shemot', 15, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('beshalach', 'Beshalach', 'בשלח', 'Shemot', 16, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('yitro', 'Yitro', 'יתרו', 'Shemot', 17, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('mishpatim', 'Mishpatim', 'משפטים', 'Shemot', 18, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('terumah', 'Terumah', 'תרומה', 'Shemot', 19, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('tetzaveh', 'Tetzaveh', 'תצוה', 'Shemot', 20, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('ki-tisa', 'Ki-Tisa', 'כי תשא', 'Shemot', 21, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vayakhel', 'Vayakhel', 'ויקהל', 'Shemot', 22, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('pekudei', 'Pekudei', 'פקודי', 'Shemot', 23, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vayikra', 'Vayikra', 'ויקרא', 'Vayikra', 24, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('tzav', 'Tzav', 'צו', 'Vayikra', 25, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('shemini', 'Shemini', 'שמיני', 'Vayikra', 26, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('tazria', 'Tazria', 'תזריע', 'Vayikra', 27, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('metzora', 'Metzora', 'מצורע', 'Vayikra', 28, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('acharei-mot', 'Acharei-Mot', 'אחרי מות', 'Vayikra', 29, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('kedoshim', 'Kedoshim', 'קדושים', 'Vayikra', 30, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('emor', 'Emor', 'אמור', 'Vayikra', 31, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('behar', 'Behar', 'בהר', 'Vayikra', 32, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('bechukotai', 'Bechukotai', 'בחקתי', 'Vayikra', 33, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('bamidbar', 'Bamidbar', 'במדבר', 'Bamidbar', 34, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('naso', 'Naso', 'נשא', 'Bamidbar', 35, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('behaalotecha', 'Behaalotecha', 'בהעלותך', 'Bamidbar', 36, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('shelach', 'Shelach', 'שלח־לך', 'Bamidbar', 37, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('korach', 'Korach', 'קרח', 'Bamidbar', 38, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('chukat', 'Chukat', 'חקת', 'Bamidbar', 39, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('balak', 'Balak', 'בלק', 'Bamidbar', 40, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('pinchas', 'Pinchas', 'פינחס', 'Bamidbar', 41, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('matot', 'Matot', 'מטות', 'Bamidbar', 42, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('masei', 'Masei', 'מסעי', 'Bamidbar', 43, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('devarim', 'Devarim', 'דברים', 'Devarim', 44, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vaetchanan', 'Vaetchanan', 'ואתחנן', 'Devarim', 45, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('eikev', 'Eikev', 'עקב', 'Devarim', 46, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('reeh', 'Reeh', 'ראה', 'Devarim', 47, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('shoftim', 'Shoftim', 'שופטים', 'Devarim', 48, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('ki-tetze', 'Ki-Tetze', 'כי־תצא', 'Devarim', 49, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('ki-tavo', 'Ki-Tavo', 'כי־תבוא', 'Devarim', 50, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('nitzavim', 'Nitzavim', 'נצבים', 'Devarim', 51, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vayelech', 'Vayelech', 'וילך', 'Devarim', 52, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('haazinu', 'Haazinu', 'האזינו', 'Devarim', 53, 'Porção semanal — conteúdo detalhado em preparação.', false),
  ('vezot-haberakhah', 'Vezot-Haberakhah', 'וזאת הברכה', 'Devarim', 54, 'Porção semanal — conteúdo detalhado em preparação.', false)
-- Só preenche slugs que ainda não existem (não sobrescreve PDFs/textos que você já criou).
ON CONFLICT (slug) DO NOTHING;
